# Generated by Django 5.2.6 on 2025-10-02 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cchoice', models.CharField(choices=[('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Surgeon', 'Surgeon'), ('Immunology', 'Immunology')], max_length=20)),
                ('dname', models.CharField(max_length=20)),
                ('demail', models.EmailField(max_length=254, unique=True)),
                ('qfc', models.CharField(max_length=40)),
                ('charges', models.IntegerField()),
                ('address', models.TextField()),
                ('dtime', models.TimeField()),
                ('exp', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
