# Generated by Django 5.2.6 on 2025-10-02 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dctime',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
