# Generated by Django 5.2.6 on 2025-10-03 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_doctor_dctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dimage',
            field=models.ImageField(default='', upload_to='doctor/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dtime',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
