# Generated by Django 5.2.6 on 2025-10-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_doctor_dimage_alter_doctor_dtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='dctime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='dtime',
            new_name='start_time',
        ),
    ]
